### ISSUE TITLE
Test failling on travis and jenkins too

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-input-redis#37]
https://travis-ci.org/logstash-plugins/logstash-input-redis/builds/11697475
```
The command "bundle exec rspec spec --order rand" exited with 0.
13.72s$ bundle exec rspec spec --order rand -t redis
Using Accessor#strict_set for specs
Run options:
  include {:redis=>true}
  exclude {:socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
F...
Failures:
  1) LogStash::Inputs::Redis for the subscribe data_types runtime for pattern_channel data_type real redis calling the run method, adds events to the queue
     Failure/Error: expect(accumulator.size).to eq(2)
       
       expected: 2
            got: 0
       
       (compared using ==)
     # ./spec/inputs/redis_spec.rb:295:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'
Finished in 5.76 seconds (files took 1.83 seconds to load)
4 examples, 1 failure
Failed examples:
rspec ./spec/inputs/redis_spec.rb:287 # LogStash::Inputs::Redis for the subscribe data_types runtime for pattern_channel data_type real redis calling the run method, adds events to the queue
Randomized with seed 938
```

**Comment by ph** [comment]
@suyograo I think the latest changes to the batch and the added test created this issue?

**Comment by colinsurprenant** [comment]
similar issue on the last 2.3.1 release branch, this failure is intermittent.
```
  1) LogStash::Inputs::Redis runtime for list data_type calling the run method, adds events to the queue
     Failure/Error: expect(accumulator.size).to be > 0
       expected: > 0
            got:   0
     # ./vendor/bundle/jruby/1.9/gems/logstash-input-redis-2.0.5/spec/inputs/redis_spec.rb:123:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:72:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:248:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:243:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:173:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:75:in `run'

Finished in 3 minutes 9.8 seconds (files took 16.1 seconds to load)
1113 examples, 1 failure

Failed examples:

rspec ./vendor/bundle/jruby/1.9/gems/logstash-input-redis-2.0.5/spec/inputs/redis_spec.rb:108 # LogStash::Inputs::Redis runtime for list data_type calling the run method, adds events to the queue

Randomized with seed 29087
```

**Comment by colinsurprenant** [comment]
@guyboertje I believe you were the last to make significant changes here, maybe you have an idea?
